name: CI
on:
  push:
    - main
jobs:
  build:
    name: Test, lint and build. Then deploy Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Lint
        run: yarn lint

      - name: Build Library
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ghpages # The branch the action should deploy to.
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
